# Generated by Django 3.1.4 on 2021-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
