# Generated by Django 3.1.4 on 2021-01-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20210103_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
